---
- hosts: all
  vars:
    TF_BINARY_URL: "https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.13.1-cp35-cp35m-linux_x86_64.whl"
    TF_VERSION : 1.13.1
    EXAMPLE_FILE : "https://raw.githubusercontent.com/horovod/horovod/master/examples/tensorflow_mnist.py"

  tasks:
    - name: Check if tensorflow exists
      command: python3 -c "import tensorflow"
      register: tf_env_check
      ignore_errors: yes

    - name: Check tensorflow version
      command: python3 -c "import tensorflow as tf; print(tf.__version__)"
      register: tf_version
      ignore_errors: yes

    - name: Execute script if tensorflow environment doesn't exist
      command: sudo pip3 install --upgrade {{ TF_BINARY_URL }}
      when: tf_env_check.stderr.find('ImportError') != -1 or tf_version.stdout.find('{{ TF_VERSION }}') == -1

    - name: Horovod Install(or re-install)
      command: pip3 install -v --no-cache-dir horovod

    - name: Download Tensorflow Example
      get_url:
        url: "{{ EXAMPLE_FILE }}"
        dest: /home/ubuntu/tensorflow-train.py

